export enum ErrorTypeE {
  NOT_FOUND = "NOT_FOUND",
  NOT_MATCH = "PASSWORD_NOT_MATCH",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  INVALID_REQUEST = "INVALID_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  DUPLICATED = "USER_ALREADY_EXISTS",
}
